services:
  python-app:
    networks: 
      - cep
    image: python:3.11-slim
    container_name: cep-app-python
    labels:
      cep.proxy.port: "8069"
    volumes:
      - ./app:/app
    working_dir: /app
    command: python -m http.server 8069
    ports:
      - "8069:8069"
    restart: unless-stopped
