services:
  redis:
    image: redis:7-alpine
    container_name: my-redis
    ports:
      - "6379:6379"
    volumes:
      - default_redis-data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

volumes:
  default_redis-data:
    external: true

