services:
  python-app:
    image: python:3.11-slim
    container_name: my-python-app
    volumes:
      - ./app:/app
    working_dir: /app
    command: python -m http.server 8069
    ports:
      - "8069:8069"
    restart: unless-stopped
